name: Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run flake8 Syntax Check
        run: flake8 --exclude=venv,.git
