name: Syntax Check

on:
  push:
    branches:
      - main

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Pylint
      run: pip install pylint

    - name: Run Pylint
      run: pylint appcar5.py
